### ISSUE TITLE
Uncaught Error: ENOENT, no such file or directory '/home/webs/.wine'

### ISSUE THREAD

**Issue by weber** [rev087/fancy-new-file#19]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.165.0
**System**: linux 3.18.0-031800-generic
**Thrown From**: [fancy-new-file](https://github.com/rev087/fancy-new-file) package, v0.7.0

### Stack Trace

Uncaught Error: ENOENT, no such file or directory '/home/webs/.wine'

```
At /home/webs/opt/atom/resources/atom/common/lib/asar.js:52

Error: ENOENT, no such file or directory '/home/webs/.wine'
  at Error (native)
  at fs.statSync (fs.js:726:18)
  at Object.fs.statSync (/home/webs/opt/atom/resources/atom/common/lib/asar.js:155:14)
  at /home/webs/.atom/packages/fancy-new-file/lib/fancy-new-file-view.coffee:85:24
  at Array.forEach (native)
  at /home/webs/.atom/packages/fancy-new-file/lib/fancy-new-file-view.coffee:73:15
  at Object.oncomplete (fs.js:93:15)

```

### Commands

```
     -0:00.0 fancy-new-file:toggle (input.hidden-input)
```

### Config

```
{
  "core": {
    "disabledPackages": [
      "metrics"
    ]
  }
}
```

### Installed Packages

```coffee
# User
fancy-new-file, v0.7.0

# Dev
No dev packages
```

/cc @atom/core

**Comment by Trudko** [comment]
@weber Do you still experience this issue?
